config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 200}
  validates :description, presence: true, length: {minimum: 10}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 5, maximum: 200 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :logged_in?
  def logged_in?
    !!current_user
  end

  def require_user 
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 10).page(params[:page]).order('created_at DESC')
  end

  def new 
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to article_path(@article)
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to article_path(@article)
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private 

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:error] = "You can only edit or delete your own articles"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def show
    @category = Category.find(params[:id])
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5).page(params[:page]).order('created_at ASC')
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created."
      redirect_to @category
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully."
      redirect_to @category
    else
      render "edit"
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
    
  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:error] = "Only admins can perform this action."
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to user
    else
      flash.now[:error] = "The email and password combination was incorrect."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5).page(params[:page]).order('created_at DESC')
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id
      flash[:notice] = "Hi #{@user.username}, welcome to the blog."
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User was updated successfully."
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted."
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user 
    if current_user != @user && !current_user.admin?
      flash[:error] = "You can only edit or delete your own profile."
      redirect_to @user
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"
      when "error"
        "alert-danger"
      when "alert"
        "alert-warning"
      when "notice"
        "alert-info"
      else
        flash_type.to_s
      end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articlelist.html.erb
<div class="row align-items-center g-lg-5 py-3">
  <div class="col-lg-7 text-center text-lg-start">
    <h1 class="display-4 fw-bold lh-1 mb-3"><%= link_to obj.first.title, article_path(obj.first), class: "article-index-link" %></h1>
  </div>
  <div class="col-md-10 mx-auto col-lg-5">
    <% if obj.first.created_at == obj.first.updated_at %>
      <p class="timestamp-text">Created <%= time_ago_in_words(obj.first.created_at) %> ago</p>
    <% else %>
      <p class="timestamp-text">Updated <%= time_ago_in_words(obj.first.updated_at) %> ago</p>
    <% end %>
    <% if obj.first.categories.any? %>
        <p>
          <% obj.first.categories.each do |cat| %>
            <span class="timestamp-text ml-1"><%= link_to cat.name.upcase, category_path(cat), class: "cat-text" %> </span>
          <% end %>
        </p>
      <% end %>
    <p><%= truncate(obj.first.description, length: 500) %></p>
  </div>
</div>

<div class="row g-lg-5 my-2 py-5">
  <% obj[1..-1].each do |x| %>
    <div class="col-lg-4 text-center text-lg-start">
      <% if x.created_at == x.updated_at %>
        <p class="timestamp-text">Created <%= time_ago_in_words(x.created_at) %> ago</p>
      <% else %>
        <p class="timestamp-text">Updated <%= time_ago_in_words(x.updated_at) %> ago</p>
      <% end %>
      <% if x.categories.any? %>
        <p>
          <% x.categories.each do |cat| %>
            <span class="timestamp-text ml-1"><%= link_to cat.name.upcase, category_path(cat), class: "cat-text" %> </span>
          <% end %>
        </p>
      <% end %>
      <h1 class="display-6 fw-bold lh-1 mb-3"><%= link_to x.title, article_path(x), class: "article-index-link" %></h1>
      <p><%= truncate(x.description, length: 150) %></p>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, data: {turbo:false}, local: true) do |f| %>
  <div class="form-group col-12">
    <%= f.label :title, class: "form-label col-12" %>
    <%= f.text_field :title, class: "col-12 form-field", placeholder: "Title of the article" %>
  </div>
  <div class="form-group col-12">
    <%= f.label :description, "Text", class: "form-label col-12" %>
    <%= f.text_area :description, class: "col-12 form-field", placeholder: "Text of the article", rows: 10 %>
  </div>
  <div class="form-group col-12">
    <%= f.label :category, "Category", class: "form-label col-12" %>
    <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Select matching categories from the list" }, { multiple: true, class: "custom-select cat-select" }) %>
  </div>
  <div class="form-group col-12">
    <%= f.submit class: "btn btn-submit" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render "shared/errors", obj: @article %>

<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-lg-6 text-center text-lg-start">
      <h1 class="display-4 fw-bold lh-1 mb-3">Edit an article</h1>
      <p class="col-lg-10 fs-5">Feel free to edit any article on this site. The edit will be reflected on the blog page.</p>
    </div>
    <div class="col-md-10 mx-auto col-lg-6">
      <%= render "form" %>
    </div>
  </div>
</div>

<div class="container d-flex align-items-center justify-content-center">
  <div class="row">
    <%= link_to "Cancel and return to articles list", articles_path, class: "fs-6 back-link" %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="flickr_pagination mb-5">
    <%= will_paginate @articles, :container => false %>
  </div>
  <%= render "articlelist", obj: @articles%>
   <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

  <% if logged_in? %>
    <div class="row align-items center g-lg-5 btns">
      <div class="text-center mx-auto col-lg-10">
        <%= link_to "Submit new article", new_article_path, class: "new-btn" %>
      </div>
    </div>
  <% end %>
  
</div>

app/views/articles/new.html.erb
<%= render "shared/errors", obj: @article %>

<div class="container col-xl-10 col-xxl-8 px-4 py-1">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-lg-6 text-center text-lg-start">
      <h1 class="display-4 fw-bold lh-1 mb-3">Submit a new article</h1>
      <p class="col-lg-10 fs-5">Feel free to submit a new article about anything you please. It will show up on top of the blog page.</p>
    </div>
    <div class="col-md-10 mx-auto col-lg-6">
      <%= render "form" %>
    </div>
  </div>
</div>

<div class="container d-flex align-items-center justify-content-center">
  <div class="row">
    <%= link_to "Cancel and return to articles list", articles_path, class: "fs-6 back-link" %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-lg-10 text-center mx-auto">
      <h1 class="display-4 fw-bold lh-1 mb-3"><%= @article.title %></h1>
    </div>
  </div>
  <div class="row align-items center g-lg-5">
    <div class="col-md-10 mx-auto col-lg-10 article-text">
      <div class="d-flex justify-content-between">
        <span class="timestamp-text">By <%= link_to @article.user.username.upcase, user_path(@article.user), class: "timestamp-link" %></span>
        <% if @article.created_at == @article.updated_at %>
          <span class="timestamp-text">Created <%= time_ago_in_words(@article.created_at) %> ago</span>
        <% else %>
          <span class="timestamp-text">Updated <%= time_ago_in_words(@article.updated_at) %> ago</span>
        <% end %>
      </div>
      <p><%= simple_format(@article.description) %></p>
      <span class="stretch-span"></span>
      <div class="d-flex justify-content-end mt-2">
        <% if @article.categories.any? %>
        <p>
          <% @article.categories.each do |cat| %>
            <span class="timestamp-text ml-1"><%= link_to cat.name.upcase, category_path(cat), class: "cat-text" %> </span>
          <% end %>
        </p>
      <% end %>
      </div>
    </div>
  </div>

  <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
    <div class="row align-items center g-lg-5 btns">
      <div class="text-center mx-auto col-lg-10">
        <%= link_to "Edit", edit_article_path(@article), class: "edit-btn" %>
        <%= button_to "Delete", article_path(@article), method: :delete, class: "del-btn", form: { data: { turbo_confirm: "Are you sure?" }, class: "d-inline" } %>
      </div>
    </div>
  <% end %>

</div>

app/views/categories/_category.html.erb
<%= link_to category.name.upcase, category_path(category), class: "cat-text" %>

app/views/categories/_form.html.erb
<%= form_with(model: @category, data: {turbo:false}, local: true) do |f| %>
  <div class="form-group col-12">
    <%= f.label :name, "Category name", class: "form-label col-12" %>
    <%= f.text_field :name, class: "col-12 form-field", placeholder: "Name of the category" %>
  </div>
  <div class="form-group col-12">
    <%= f.submit class: "btn btn-submit" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render "shared/errors", obj: @category %>

<div class="container col-xl-10 col-xxl-8 px-4 py-1">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-lg-6 text-center text-lg-start">
      <h1 class="display-4 fw-bold lh-1 mb-3">Edit category</h1>
      <p class="col-lg-10 fs-5">Want to change the name of the category? You can do it here.</p>
    </div>
    <div class="col-md-10 mx-auto col-lg-6">
      
      <%= render "form" %>

    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-lg-10 text-center mx-auto">
      <h1 class="display-4 fw-bold lh-1 mb-3">Categories</h1>
    </div>
  </div>
  <div class="flickr_pagination mb-5 mt-5">
    <%= will_paginate @categories, :container => false %>
  </div>
  <div class="row align-items-center g-lg-5">
    <% @categories.each do |category| %>
      <div class="col-lg-12 text-lg-start">
        <h1 class="display-6 text-center fw-bold lh-1 mb-3"><%= link_to category.name, category, class: "article-index-link" %></h1>
        <p class="text-center"><%= pluralize(category.articles.count, "articles") %></p>
        <% if category != @categories.last %>
          <hr class="users-hr mt-5">
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="flickr_pagination mb-5 mt-5">
    <%= will_paginate @categories, :container => false %>
  </div>
</div>

app/views/categories/new.html.erb
<%= render "shared/errors", obj: @category %>

<div class="container col-xl-10 col-xxl-8 px-4 py-1">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-lg-6 text-center text-lg-start">
      <h1 class="display-4 fw-bold lh-1 mb-3">Create a new category</h1>
      <p class="col-lg-10 fs-5">Need a new category for your article? Create it here.</p>
    </div>
    <div class="col-md-10 mx-auto col-lg-6">
      
      <%= form_with(model: @category, data: {turbo:false}, local: true) do |f| %>
        <div class="form-group col-12">
          <%= f.label :name, "Category name", class: "form-label col-12" %>
          <%= f.text_field :name, class: "col-12 form-field", placeholder: "Name of the category" %>
        </div>
        <div class="form-group col-12">
          <%= f.submit class: "btn btn-submit" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-lg-10 text-center mx-auto">
      <h1 class="display-4 fw-bold lh-1 mb-3"><%= @category.name %></h1>
    </div>
  </div>

  <div class="row align-items center g-lg-5">
    <div class="flickr_pagination">
      <%= will_paginate @category.articles.paginate(page: params[:page], per_page: 10).page(params[:page]).order('created_at DESC'), :container => false %>
    </div>
    <% if !@category.articles.last.nil? %>
      <%= render "articles/articlelist", obj: @category.articles.paginate(page: params[:page], per_page: 10).page(params[:page]).order('created_at DESC')
 %>
    <% else %>
      <p class="text-center">This category contains no articles.</p>
    <% end %>
    <div class="flickr_pagination">
      <%= will_paginate @category.articles.paginate(page: params[:page], per_page: 10).page(params[:page]).order('created_at DESC'), :container => false %>
    </div>
  </div>

  <% if logged_in? && current_user.admin? %>
    <div class="row align-items center g-lg-5 btns">
      <div class="text-center mx-auto col-lg-10">
        <%= link_to "Edit category name", edit_category_path(@category), class: "edit-btn" %>
      </div>
    </div>
  <% end %>

</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex justify-content-center align-items-center">
      <span>© 2022 Adriana Staudova</span>
    </div>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 d-flex flex-direction-column justify-content-center">
  <% if flash.any? %>
      <% flash.each do |name, msg| %>
        <% if name == "error" %>
          <div class="col-10 alert alert-danger alert-dismissible fade show" role="alert">
        <% else %>
          <div class="col-10 alert alert-success alert-dismissible fade show" role="alert">
        <% end %>
        <%= msg %>
      <% end %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-transparent py-3">
  <div class="container-fluid">
    <%= link_to "THE BLOG", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "BLOG", articles_path, class: (current_page?(articles_path) ? "nav-link under-link active" : "nav-link under-link") %>
        </li>

        <li class="nav-item dropdown">
              <% if current_page?(categories_path) %>
                <a class="nav-link under-link active dropdown-toggle" id="dropdown-user" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% else %>
                <a class="nav-link under-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% end %>
              CATEGORIES
            </a>
            <ul class="dropdown-menu dropdown-menu-end text-center" aria-labelledby="navbarDropdown">
              <li><%= link_to "VIEW CATEGORIES", categories_path, class: "nav-link drop-link" %></li>
              <% if logged_in? && current_user.admin? %>
                <li><%= link_to "ADD CATEGORY", new_category_path, class: "nav-link drop-link" %></li>
              <% end %>
            </ul>
          </li>

        <li class="nav-item">
          <%= link_to "WRITERS", users_path, class: (current_page?(users_path) ? "nav-link under-link active" : "nav-link under-link") %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <li class="nav-item dropdown">
              <% if current_page?(user_path(current_user)) || current_page?(edit_user_path(current_user)) %>
                <a class="nav-link under-link active dropdown-toggle" id="dropdown-user" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% else %>
                <a class="nav-link under-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% end %>
              <%= "(admin) " if current_user.admin? %><%= current_user.username.upcase %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end text-center" aria-labelledby="navbarDropdown">
              <li><%= link_to "VIEW PROFILE", user_path(current_user), class: "nav-link drop-link" %></li>
              <li><%= link_to "EDIT PROFILE", edit_user_path(current_user), class: "nav-link drop-link" %></li>
              <li><%= link_to "NEW ARTICLE", new_article_path, class: "nav-link drop-link" %></li>
              <li><%= button_to "DELETE PROFILE", user_path(current_user), class: "drop-btn", form: { data: { turbo_confirm: "Are you sure?" }, class: "d-inline" }, method: :delete %></li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "LOG OUT", logout_path, class: "nav-link under-link", method: "delete" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "LOG IN", login_path, class: (current_page?(login_path) ? "nav-link under-link active" : "nav-link under-link") %>
          </li>
          <li class="nav-item">
            <%= link_to "SIGN UP", signup_path, class: (current_page?(signup_path) ? "nav-link signup-link active" : "nav-link signup-link") %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "custom.css" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="https://fonts.cdnfonts.com/css/souvenir" rel="stylesheet">
    <link href="https://fonts.cdnfonts.com/css/futura-std-4" rel="stylesheet">
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>
    <%= yield %>
  </body>

  <%= render "layouts/footer" %>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

<p>
  <%= link_to "Articles list", articles_path %> |
  <%= link_to "Home page", root_path %>
</p>

app/views/pages/home.html.erb
<div class="container col-xxl-8 px-4 py-5">
  <div class="row flex-lg-row-reverse align-items-center justify-content-center g-5 py-5">
    <div class="col-10 col-sm-8 col-lg-6">
      <%= image_tag "blog.svg", class: "d-block mx-lg-auto img-fluid", alt: "Blog Hero Image", loading: "lazy" %>
    </div>
    <div class="col-lg-6">
      <h1 class="display-5 fw-bold lh-1 mb-3">This is a simple blog featuring a few articles from TechCrunch</h1>
      <p class="lead">Built with Ruby on Rails 7, with Bootstrap helping out in the front end and some illustrations from undraw.co.</p>
      <%= link_to "SIGN UP", signup_path, class: "signup-home"%>
      
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-lg-10 text-center mx-auto">
      <h1 class="display-4 fw-bold lh-1 mb-3">Writers</h1>
    </div>
  </div>
  <div class="flickr_pagination mb-5 mt-5">
    <%= will_paginate @users, :container => false %>
  </div>
  <div class="row align-items-center g-lg-5">
    <% @users.each do |user| %>
      <div class="col-lg-12 text-lg-start">
        <h1 class="display-6 text-center fw-bold lh-1 mb-3"><%= link_to user.username, user, class: "article-index-link" %></h1>
        <p class="text-center"><%= pluralize(user.articles.count, "article") %></p>
        <div class="row align-items center g-lg-5">
          <div class="text-center mx-auto col-lg-10">
            <%= link_to "View blog", user, class: "small-btn" %>
            <% if logged_in? && user == current_user %>
              <%= link_to "Edit profile", edit_user_path(user), class: "small-btn" %>
            <% end %>
          </div>
        </div>
        <% if user != @users.last %>
          <hr class="users-hr mt-5">
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="flickr_pagination mb-5 mt-5">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-lg-10 text-center mx-auto">
      <h1 class="display-4 fw-bold lh-1 mb-3"><%= @user.username %>'s blog</h1>
    </div>
  </div>
  <div class="row align-items center g-lg-5">
    <div class="flickr_pagination">
      <%= will_paginate @user.articles.paginate(page: params[:page], per_page: 10).page(params[:page]).order('created_at DESC'), :container => false %>
    </div>
    <% if !@user.articles.last.nil? %>
      <%= render "articles/articlelist", obj: @user.articles.paginate(page: params[:page], per_page: 10).page(params[:page]).order('created_at DESC')
 %>
    <% else %>
      <p class="text-center">This user has not written any articles yet.</p>
    <% end %>
    <div class="flickr_pagination">
      <%= will_paginate @user.articles.paginate(page: params[:page], per_page: 10).page(params[:page]).order('created_at DESC'), :container => false %>
    </div>
  </div>

  <% if logged_in? && @user == current_user %>
    <div class="row align-items center g-lg-5 btns">
      <div class="text-center mx-auto col-lg-10">
        <%= link_to "Submit new article", new_article_path, class: "edit-btn" %>
        <%= link_to "Edit profile", edit_user_path(@user), class: "edit-btn" %>
        <%= button_to "Delete profile", user_path(@user), method: :delete, class: "del-btn", form: { data: { turbo_confirm: "Are you sure?" }, class: "d-inline" } %>
      </div>
    </div>
  <% end %>

  <% if logged_in? && current_user.admin?%>
    <div class="row align-items center g-lg-5 btns">
      <div class="text-center mx-auto col-lg-10">
        <%= button_to "Delete profile", user_path(@user), method: :delete, class: "del-btn", form: { data: { turbo_confirm: "Are you sure?" }, class: "d-inline" } %>
      </div>
    </div>
  <% end %>

</div>